name: DCAugusta
favicon: null
layout_spectrum: 1
typography_spectrum: 0.81759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8e8e8e'
    - '#3a3a3a'
    - '#ac142d'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
